#!/bin/bash

FILENAME=$0
FILENAME=${FILENAME##*/}

Version () {
echo "$FILENAME version 0.2"
      echo "GNU License <http://gnu.org/licenses/gpl.html>."
      echo "This is a free software! You are allowed to change and redistribute it for free."
      echo "Written by Luan Rodrigues - https://github.com/luoldrigues/sup"
      echo
      exit 0
}

Help () {
   echo "Usage: $FILENAME {COMMAND} <SERVICE> [OPTIONS...]"
   echo
   echo "COMMAND:"
   echo "  keepup           Try to KEEP the service UP"
   echo
   echo "OPTIONS:"
   echo "  -h, --help       Show this help"
   echo "  -v, --verbose    Verbosely list processed"
   echo "      --usage      Give a short usage message"
   echo "      --version    Print program version"
   echo
   echo "Examples:"
   echo "   $FILENAME keepup httpd --verbose"
   echo "   $FILENAME keepup mariadb -v"
   echo "   $FILENAME keepup firewalld"
   echo "   $FILENAME --help"
   echo
   echo "You might use this program in your crontab"
   echo "Cron example:"
   echo "  */15 * * * * $0 keepup mariadb"
   echo "  The line above execute every 15 minutes to check the MariaDB service"
   echo "  For more details see 'man crontab'"
   echo
   exit 0
}

Usage () {
  echo "Usage: $FILENAME {keepup} <SERVICE> [--help] [--verbose] [--usage] [--version]"
  echo
  echo "Examples:"
  echo "   $FILENAME keepup httpd --verbose"
  echo "   $FILENAME keepup mariadb -v"
  echo "   $FILENAME keepup firewalld -v"
  echo "   $FILENAME --help"
  echo
  exit 0
}

ACTION=""
SERVICE=""
VERBOSE=0

while true; do
  case $1 in
    --help|-h)
      Help
    ;;
    --usage)
      Usage
    ;;
    --version)
      Version
    ;;
    --verbose|-v)
      VERBOSE=1
    ;;
    keepup)
      ACTION=$1
      if [ "$SERVICE" = "" ]; then
        SERVICE=$2
        shift
      fi
    ;;
    *)
      break
    ;;
  esac
  shift
done

# Remove '.service' extension
SERVICE=${SERVICE%.service}

# Service Validation
which $SERVICE &> /dev/null
if [ $? -ne 0 ]; then
  # Validing group services
  cat "/usr/lib/systemd/system/"$SERVICE".service" &> /dev/null
  if [ $? -ne 0 ]; then
    echo "Invalid Service"
    echo "Try $0 [--help|-h]"
    echo
    exit 3
  fi
fi

if [ "$SERVICE" = "" ]; then
  echo "Syntax Error"
  echo "Try $0 [--help]"
  echo
  exit 1
fi

case $ACTION in
   keepup)
     systemctl status $SERVICE &> /dev/null
     if [ $? -eq 0 ]; then
       # it is working well
       if [ $VERBOSE -eq 1 ]; then
         echo "OK: $SERVICE is working well"
         echo
       fi
     else
       # it is not working; trying to restart
       if [ $VERBOSE -eq 1 ]; then
         echo "FAIL: $SERVICE is not working"
         echo "Restarting $SERVICE"
       fi
       systemctl restart $SERVICE
       # checking if it is OK
       systemctl status $SERVICE &> /dev/null
       if [ $? -eq 0 ]; then
         if [ $VERBOSE -eq 1 ]; then
           echo "OK: $SERVICE is working well"
         fi
       else
         echo "FAIL: $SERVICE is not working"
         echo 
         exit 1
       fi
     fi
   ;;
   *)
     echo "Invalid Option"
     echo "Try $0 [--help]"
     echo
     exit 2
   ;;
esac

